### ISSUE TITLE
skia doesn't build completely on the first pass

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#176]
Building the skia library requires two passes.  This is the reason for the two step build.  We should fix this problem and make third_party a dependency of the main build so that the build can be completed in a single step.

Steps to reproduce:

1. Start from a clean build (remove any NATIVE-* directories).
1. Run `scons -j8 optimize=1 third_party`.  Note that the skia library builds as a part of this command.
1. Run `scons -j8 optimize=1`.  Note that the skia library builds again but runs different commands.

Once we fix this issue so that skia builds in a single pass, we can make the third_party build a dependency of the main build and leave it to scons to ensure that third_party is built when appropriate.  This will allow us to build with a single step and possibly make builds faster.

**Comment by tst-ccamp** [comment]
Fixed in #175

**Comment by tst-lsavoie** [comment]
@tst-ccamp technically this is still an issue, but it's masked by the fact that the `build` target calls both of the targets listed in the description. Is that why you closed it?
