### ISSUE TITLE
Keep "Queued" when building terrain resource with large number of src files

### ISSUE THREAD

**Issue by protodonuts** [google/earthenterprise#182]
1. In Fusion, create a new terrain resource, add a total of 2,413 valid GeoTiff files (12.0 GB), save as "res/alot" in asset root.
2. Build the resource.

Expected: Status turns to "InProgress", log file shows the specific progress.

Found:
- VersionProperties shows "CHILD: KRP" as "Queued" for hours, with no log text updated or alert popup.
- "INPUT: Source" and "INPUT: Mosaic" Succeeded normally.

`getop` shows
```
FUSION VERSION: 5.1.3
MASTER: mycomputer    ASSET ROOT: /gevol/assets

Active on mycomputer (max = 4):
Waiting:
  res/alot.ktasset/product.kta?version=1
     Not enough disk space to make reservation for output files.Task res/alot.ktasset/product.kta?version=1...

Fusion processes on this host:
1652     00:00:07 gesystemmanager
1655     00:00:03 geresourceprovi

Number of cached assets: 175
Number of cached asset versions: 204
```
But my disk has ENOUGH free space ( up to 400 GB ).

I rearranged these source files into 3 different resources ( about 800 files for each ). They were built normally.

QUESTION: Should I change the value of `reserveSpace` in `$assetroot/.config/volumes.xml`?

**Comment by tst-ccamp** [comment]
It would be a big benefit to improve error reporting like this in the UI. I'll open a ticket to do that. As for your question about the volumes.xml file, I'm afraid I don't know the answer. @asmitaw @andreisel @dattapm Do any of you have an idea about that?

**Comment by tst-ccamp** [comment]
Also, the fact that the resources would build if split into 3, but not if all combined may indicate a bug. But, since there are so many files, it may be that by including them all in the same resource the footprint is just too big. The process will mosaic all the images together into one rectangular image. If that would create significant gaps of blank space, that might explain why it would take up too much space if they are all combined into one resource. It's best to make sure your input files are all in the same general, roughly rectangular area per resource.

**Comment by andreisel** [comment]
@protodonuts 
+1 on @tst-ccamp advice - put into mosaic files that form one cluster - images touch each other.
GEE Fusion when importing mosaic checks it for multiple clustering and also check area of mosaic vs sum of areas of source images and report in INPUT: source and/or INPUT:Mosaic logs this information. 
It works not for all projections, but you can check if anything reported in logs. Also, you can preview mosaic in Fusion UI - visually check clustering.

**Comment by protodonuts** [comment]
I tried another terrain resource with 1,600 files (8.9 GB) that cover areas in the same rectangle together. It works well. The resource were built normally. I think things are like what you said.

@tst-ccamp @andreisel Thanks for your help.

**Comment by asmitaw** [comment]
QUESTION: Should I change the value of reserveSpace in $assetroot/.config/volumes.xml - regarding this general question , I am not sure if we change value that increases the allocation of asset volume.
If it was the case, it would be surfaced in the installation or some option than changing the underlying files in very raw way. I would not touch the values in the assets files.

**Comment by tst-ahernandez** [comment]
It looks like this issue has been resolved. Closing!

**Comment by protodonuts** [comment]
@tst-ahernandez Not exactly... the BUG still exists that NOTHING is reported to GUI user about why the building process is "Queued" forever.

#216 shows the same problem.

**Comment by bradh** [comment]
@protodonuts I don't think #216 is the same issue - the OP described it as a single GeoTIFF image, not a large composite / mosaic.

**Comment by protodonuts** [comment]
@bradh It looks the same that some error happened background is blocking the building process, while GUI user get nothing but an everlasting "Queued".

**Comment by tst-ccamp** [comment]
Let's reopen this issue until we have a follow-up issue open to specifically address the problem of not displaying that the underlying problem is not communicated to the UI.

**Comment by tst-ccamp** [comment]
@protodonuts I've just created https://github.com/google/earthenterprise/issues/221. Does that capture the issue adequately?

**Comment by protodonuts** [comment]
Sure, looks good. Thanks : ) @tst-ccamp
